name: Macos-CI

'on':
  - push
  - pull_request

permissions:
  contents: read

jobs:
  ci:
    name: macos-llvm-${{ matrix.config.name }}-${{ matrix.variant.name }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: release, extra_flags: '' }
          - { name: debug,   extra_flags: '-DCMAKE_BUILD_TYPE=Debug' }
        variant:
          - { name: plain,    flags: '' }
          - { name: enhanced, flags: '-DROARING_CPP_ENHANCED=ON' }

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: For ROARING_CPP_ENHANCED https://needful.metaeducation.com/setup
        if: ${{ matrix.variant.name == 'enhanced' }}
        run: |
          git clone --depth 1 https://github.com/metaeducation/needful-enhanced include/roaring/needful-enhanced || true

      - name: Configure build
        run: |
          cmake \
            -S . \
            -B build \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install" \
            -DENABLE_ROARING_TESTS=ON \
            ${{ matrix.config.extra_flags }} \
            ${{ matrix.variant.flags }}

      - name: Build/test/install
        run: |
          cmake --build build
          ctest --test-dir build --output-on-failure
          cmake --install build

      - name: Build installation-find sample
        run: |
          cmake \
            -S tests/installation/find \
            -B tests/installation/find/build \
            -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/install" \
            ${{ matrix.config.extra_flags }} \
            ${{ matrix.variant.flags }}
          cmake --build tests/installation/find/build

  ci-shared:
    name: macos-llvm-shared
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Build and Test (shared)
        run: |
          cmake -S . -B buildshared -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/installshared" -DENABLE_ROARING_TESTS=ON
          cmake --build buildshared
          cmake --install buildshared
          cmake -S tests/installation/find -B tests/installation/find/buildshared -DCMAKE_PREFIX_PATH="${GITHUB_WORKSPACE}/installshared"
          cmake --build tests/installation/find/buildshared
          ./tests/installation/find/buildshared/repro
