name: OmniOS

'on':
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Build and Test on OmniOS
        uses: vmactions/omnios-vm@v1
        with:
          release: r151056
          usesh: true
          prepare: |
            set -e
            pkg install developer/cmake developer/gcc13 developer/build/gnu-make developer/versioning/git
          run: |
            set -e
            INSTALL_PREFIX="$(pwd)/install"
            INSTALL_PREFIX_SHARED="$(pwd)/installshared"

            # Release build
            cmake -S . -B build -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX}" -DENABLE_ROARING_TESTS=ON
            cmake --build build
            ctest --test-dir build --output-on-failure
            cmake --install build
            cmake -S tests/installation/find -B tests/installation/find/build -DCMAKE_PREFIX_PATH="${INSTALL_PREFIX}"
            cmake --build tests/installation/find/build

            # Shared library build
            cmake -S . -B buildshared -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX_SHARED}" -DENABLE_ROARING_TESTS=ON
            cmake --build buildshared
            cmake --install buildshared
            cmake -S tests/installation/find -B tests/installation/find/buildshared -DCMAKE_PREFIX_PATH="${INSTALL_PREFIX_SHARED}"
            cmake --build tests/installation/find/buildshared
            ./tests/installation/find/buildshared/repro

            # Debug build
            cmake -S . -B builddebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX}" -DENABLE_ROARING_TESTS=ON
            cmake --build builddebug
            ctest --test-dir builddebug --output-on-failure
            cmake --install builddebug
            cmake -S tests/installation/find -B tests/installation/find/builddebug -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH="${INSTALL_PREFIX}"
            cmake --build tests/installation/find/builddebug
