name: VS18-ARM-CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: windows-vs18-${{ matrix.arch }}
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        arch: [ARM64]

    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Configure
        run: cmake -S . -B build -A ${{ matrix.arch }} -DCMAKE_CROSSCOMPILING=1

      - name: Build
        run: cmake --build build --verbose
