name: VS18-CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  ci:
    name: windows-vs18-${{ matrix.arch }}-${{ matrix.build_type }}
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        gen: [Visual Studio 18 2026]
        arch: [Win32, x64]
        build_type: [Release, Debug]

    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Configure
        run: cmake -S . -B build -DENABLE_ROARING_TESTS=ON -DROARING_UNSAFE_FROZEN_TESTS=ON -G "${{ matrix.gen }}" -A ${{ matrix.arch }}

      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }}

      - name: Run basic tests
        working-directory: build
        run: ctest -C ${{ matrix.build_type }} --output-on-failure
